use HogwartzAccounting;

DROP TABLE IF EXISTS BANK_TRANSFER;

DROP TABLE IF EXISTS PROFESSOR_COURSE;

DROP TABLE IF EXISTS STUDENT_COURSE;

DROP TABLE IF EXISTS PROFESSOR;

DROP TABLE IF EXISTS COURSE;

DROP TABLE IF EXISTS STUDENT;

DROP TABLE IF EXISTS MANAGER;

DROP TABLE IF EXISTS CLEANER;

DROP TABLE IF EXISTS WORKS_IN;

DROP TABLE IF EXISTS MAINTENANCE_WORKER;

DROP TABLE IF EXISTS WORKER;

DROP TABLE IF EXISTS ROOM;

DROP TABLE IF EXISTS BUILDING;

DROP TABLE IF EXISTS PERSON;

DROP DATABASE IF EXISTS ExternalDatabase;

DROP VIEW IF EXISTS EXTERNAL_PERSON;

DROP VIEW IF EXISTS OLD_PERSON;

Commit;