use HogwartzAccounting;

SELECT * FROM BUILDING;

SELECT * FROM ROOM;

SELECT * FROM STUDENT;

SELECT * FROM MAINTENANCE_WORKER;

SELECT * FROM PERSON;

SELECT * FROM PROFESSOR;

SELECT * FROM WORKS_IN;

SELECT * FROM STUDENT_COURSE;

SELECT * FROM PROFESSOR_COURSE;