ALTER TABLE BANK_TRANSFER MODIFY COLUMN transfer_id INT AUTO_INCREMENT;

ALTER TABLE COURSE MODIFY COLUMN professor_pay DECIMAL(10, 2) DEFAULT 0;

ALTER TABLE COURSE MODIFY COLUMN course_cost DECIMAL(10, 2) DEFAULT 0;

ALTER TABLE BANK_TRANSFER MODIFY COLUMN transfer_id INT AUTO_INCREMENT NOT NULL;