use HogwartzAccounting;

DROP VIEW IF EXISTS EXTERNAL_PERSON;

CREATE VIEW EXTERNAL_PERSON (Age, PhoneNumber, ID, Name) AS
SELECT TIMESTAMPDIFF(YEAR, DATE_OF_BIRTH, CURDATE()), PhoneNumber, PERSON_ID, CONCAT(FIRST_NAME, " ", LAST_NAME) FROM PERSON

SELECT * FROM EXTERNAL_PERSON;

DROP VIEW IF EXISTS OLD_PERSON;

CREATE VIEW OLD_PERSON AS 
SELECT PERSON_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, BANK_ACCOUNT, NATIONAL_ID FROM PERSON

SELECT * FROM OLD_PERSON;