use HogwartzAccounting;

INSERT INTO BUILDING
SELECT BuildingID FROM ExternalDatabase.BUILDING;

INSERT INTO ROOM
SELECT RoomID, MaxCapacity, BuildingID FROM ExternalDatabase.ROOM;

DELETE FROM PROFESSOR WHERE PERSON_ID IN (SELECT ID FROM ExternalDatabase.WORKER);

DELETE FROM STUDENT WHERE PERSON_ID IN (SELECT ID FROM ExternalDatabase.WORKER);

INSERT INTO MAINTENANCE_WORKER
SELECT HireDate, ID FROM ExternalDatabase.WORKER WHERE ID IN (SELECT PERSON_ID FROM PERSON);

INSERT INTO CLEANER
SELECT Shift, ID FROM ExternalDatabase.CLEANER WHERE ID IN (SELECT ID FROM MAINTENANCE_WORKER);

INSERT INTO WORKS_IN
SELECT ID, BuildingID FROM ExternalDatabase.WORKSIN WHERE ID IN (SELECT ID FROM MAINTENANCE_WORKER);

INSERT INTO MANAGER (Devision, ID)
SELECT Department, ID FROM ExternalDatabase.MANAGER WHERE ID IN (SELECT ID FROM MAINTENANCE_WORKER);

UPDATE PERSON p1
JOIN ExternalDatabase.PERSON p2 ON p1.person_id = p2.id
SET p1.PhoneNumber = p2.PhoneNumber;

UPDATE STUDENT s1
JOIN ExternalDatabase.STUDENT s2 ON s1.person_id = s2.id
SET s1.BuildingID = s2.BuildingID, s1.RoomID = s2.RoomID;