use HogwartzAccounting;

INSERT INTO BUILDING
SELECT BuildingID FROM ExternalDatabase.BUILDING;

INSERT INTO ROOM
SELECT RoomID, MaxCapacity, BuildingID FROM ExternalDatabase.ROOM;

DELETE FROM PROFESSOR WHERE PERSON_ID IN (SELECT PERSON FROM ExternalDatabase.MAINTANENCE_WORKER);

DELETE FROM STUDENT WHERE PERSON_ID IN ExternalDatabase.MAINTANENCE_WORKER;